#include<iostream.h>
#include<conio.h>
class one
{
public:
int a;
void seta()
{
cout<<"enter a"<<endl;
cin>>a;
}
void geta()
{
cout<<a<<endl;
}
};
class two
{
public:
int b;
void setb()
{
cout<<"enter b"<<endl;
cin>>b;
}
void getb()
{
cout<<b<<endl;
}
};
class three
{
public:
int c;
void setc()
{
cout<<"enter c"<<endl;
cin>>c;
}
void getc()
{
cout<<c<<endl;
}
};
class four
{
};

void main()
{
clrscr();
getch();
}

